#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
诊断评分一致性问题
"""

print("=" * 70)
print("评分计算一致性分析")
print("=" * 70)
print()

print("问题分析:")
print("-" * 70)
print()

print("【当前逻辑】")
print()
print("1️⃣  点击'开始分析'时:")
print("   - 调用 generate_investment_advice(ticker)")
print("   - 得到 short_prediction, medium_prediction, long_prediction")
print("   - 提取: short_score, medium_score, long_score")
print("   - 公式: final_score = 5.0 + (加权平均) * 0.5")
print("   - 范围: [1.0, 10.0]")
print()

print("2️⃣  点击'生成推荐'时:")
print("   a) 如果先点过'开始分析':")
print("      - 调用 format_investment_advice(..., final_score)")
print("      - 直接使用传入的 final_score，不重新计算 ✅ 一致")
print()
print("   b) 如果直接点'生成推荐'（不先点分析）:")
print("      - format_investment_advice() 会检查是否传入了 final_score")
print("      - 如果没传，会重新调用 generate_investment_advice() 并重新计算 ✅ 应该一致")
print()

print("【潜在不一致原因】")
print()
print("⚠️  可能原因1: generate_investment_advice() 返回的三个预测对象")
print("   在大模型模式和本地模式下返回的字段结构不同")
print()
print("   ✓ 大模型模式: 返回")
print("     - short: {'technical_score': ..., ...}")
print("     - medium: {'total_score': ..., ...}") 
print("     - long: {'fundamental_score': ..., ...}")
print()
print("   ✓ 本地模式: 调用")
print("     - get_short_term_prediction(): 返回 {'technical_score': ...}")
print("     - get_medium_term_prediction(): 返回 {'total_score': ...}")
print("     - get_long_term_prediction(): 返回 {'fundamental_score': ...}")
print()
print("   ⚠️  可能在某些条件下字段名不一致！")
print()

print("【建议检查】")
print()
print("1. 在 generate_investment_advice() 中添加调试日志:")
print("   print(f'short_term_prediction keys: {short_term_prediction.keys()}')")
print("   print(f'medium_term_prediction keys: {medium_term_prediction.keys()}')")
print("   print(f'long_term_prediction keys: {long_term_prediction.keys()}')")
print()
print("2. 确保三个预测函数的返回字段一致:")
print("   - get_short_term_prediction() → 'technical_score'")
print("   - get_medium_term_prediction() → 'total_score'")
print("   - get_long_term_prediction() → 'fundamental_score'")
print()
print("3. 在 format_investment_advice() 中添加调试:")
print("   print(f'short_score from prediction: {short_score}')")
print("   print(f'medium_score from prediction: {medium_score}')")
print("   print(f'long_score from prediction: {long_score}')")
print()

print("【建议修复方案】")
print()
print("标准化返回结构，确保所有三个预测函数都返回相同的字段名:")
print()
print("  def get_*_term_prediction():")
print("      return {")
print("          'period': '...',")
print("          'score': final_score,        # ← 统一为 'score' 字段！")
print("          'technical_score': ...,      # ← 额外包含详细评分")
print("          'total_score': ...,          # ← 额外包含详细评分")
print("          'fundamental_score': ...,    # ← 额外包含详细评分")
print("          'trend': '...',")
print("          'confidence': ...,")
print("          'risk_level': '...',")
print("          'key_signals': [...],")
print("          'algorithm': '...'")
print("      }")
print()
print("然后在 format_investment_advice() 中:")
print()
print("  short_score = short_term_prediction.get('score', 0)")
print("  medium_score = medium_term_prediction.get('score', 0)")
print("  long_score = long_term_prediction.get('score', 0)")
print()
print("=" * 70)
